all:
  hosts:
    k1-v-center:
      ansible_host: <k1-v-center>
      ip: <k1-v-center>
      access_ip: <k1-v-center>
  children:
    kube-master:
      hosts:
        k1-v-center:
    kube-node:
      hosts:
        k1-v-center:
    etcd:
      hosts:
        k1-v-center:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
